### ISSUE TITLE
Workflow evaluator feeds object to CRMEntity::getInstance

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1363]
After I updated to a pretty recent version, I can't save assets anymore. I have a workflow that runs on the first save. The asset is saved to the database, but during the return, PHP throws a fatal error. Re-saving the asset works (since the workflow is configured to only run on the first save). This is the stack trace
```
Fatal error: Uncaught Error: Object of class Vtiger_Module could not be converted to string in /public_html/crmgithubtest/data/CRMEntity.php:79 Stack trace:
  #0 /public_html/crmgithubtest/data/CRMEntity.php(3898): CRMEntity::getInstance()
  #1 /public_html/crmgithubtest/modules/com_vtiger_workflow/VTJsonCondition.inc(483): CRMEntity::getcrmEntityTableAlias()
  #2 /public_html/crmgithubtest/modules/com_vtiger_workflow/VTJsonCondition.inc(30): VTJsonCondition->checkCondition()
  #3 /public_html/crmgithubtest/modules/com_vtiger_workflow/VTWorkflow.php(210): VTJsonCondition->evaluate()
  #4 /public_html/crmgithubtest/modules/com_vtiger_workflow/VTEventHandler.inc(83): Workflow->evaluate()
  #5 /public_html/crmgithubtest/include/events/VTEventTrigger.inc(146): VTWorkflowEventHandler->handleEvent()
  #6 /public_html/crmgithubtest/includ in /public_html/crmgithubtest/data/CRMEntity.php on line 79
```

**Comment by joebordes** [comment]
thanks!!
